import type React from "react";

type Segment = {
  text: string;
  relativeStart: number;
  relativeDuration: number;
};

export type GeneratedSceneItem = {
  start: number;
  duration: number;
  segments: Segment[];
  Component: React.FC<{ segments: Segment[] }>;
};

// Generated by generate-scenes-registry.js - DO NOT EDIT MANUALLY
export const generatedScenes: GeneratedSceneItem[] = [];

export const totalDurationInFrames = 150;
